"use client";

import dynamic from "next/dynamic";
import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, ArrowRight, BarChart3, CalendarDays, Check, ChevronRight, CircleHelp, Database, Gauge, Globe2, Info, LockKeyhole, Map, MapPin, Menu, MousePointer2, Play, Search, Settings2, UploadCloud, Waves, X } from "lucide-react";
import { demoGrid, demoSeries, endDate, startDate, type ViewKey, viewMeta } from "../lib/science";
import { API_URL, apiGet, flattenGrid, type MapResponse, type ProjectionResponse, type SeriesResponse, type TrendResponse } from "../lib/api";

const OceanMap = dynamic(() => import("./OceanMap"), { ssr: false });
const PlotChart = dynamic(() => import("./PlotChart"), { ssr: false });

const items: { key: ViewKey; label: string; icon: typeof Waves }[] = [
  { key: "home", label: "홈", icon: Waves }, { key: "date", label: "날짜별 해수면", icon: CalendarDays },
  { key: "point", label: "한 장소의 변화", icon: MapPin }, { key: "region", label: "영역 평균 변화", icon: BarChart3 },
  { key: "trend", label: "변화율 지도", icon: Gauge }, { key: "causes", label: "변화의 원인", icon: Activity },
  { key: "projection", label: "2100년 단순 추정", icon: Globe2 }, { key: "admin", label: "관리자", icon: Settings2 },
];

function Flow({ active = 1 }: { active?: number }) { return <div className="flow" aria-label="탐구 단계">{["입력", "분석", "결과", "해석"].map((x, i) => <div className={i <= active ? "on" : ""} key={x}><span>{i + 1}</span>{x}{i < 3 && <ChevronRight />}</div>)}</div>; }

function Field({ label, type = "date", value, onChange, min, max, step }: { label: string; type?: string; value: string | number; onChange: (v: string) => void; min?: string | number; max?: string | number; step?: string | number }) { return <label className="field"><span>{label}</span><input type={type} value={value} min={min} max={max} step={step} onChange={(e) => onChange(e.target.value)} /></label>; }

function ResultStat({ label, value, tone = "blue" }: { label: string; value: string; tone?: string }) { return <div className={`result-stat ${tone}`}><span>{label}</span><strong>{value}</strong></div>; }

function Panel({ children, title = "탐구 설정", hint }: { children: React.ReactNode; title?: string; hint?: string }) { return <aside className="control-panel"><div className="panel-title"><div><span className="step-kicker">STEP 1</span><h2>{title}</h2></div><Settings2 size={18} /></div>{hint && <p className="panel-hint">{hint}</p>}{children}</aside>; }

function Interpretation({ children, question }: { children: React.ReactNode; question: string }) { return <section className="interpret"><div className="interpret-icon"><CircleHelp /></div><div><span>해석 도움말</span><h3>{question}</h3><p>{children}</p></div></section>; }

function MapResult({ kind, selected, onPick, title, note, points, dataLabel = "시연 모드" }: { kind: "height" | "trend" | "projection" | "change"; selected?: { lat: number; lon: number }; onPick?: (lat: number, lon: number) => void; title: string; note?: string; points?: ReturnType<typeof demoGrid>; dataLabel?: string }) { const fallback = useMemo(() => demoGrid(kind), [kind]); return <div className="visual-card"><div className="visual-head"><div><span className="step-kicker">STEP 3 · 결과</span><h2>{title}</h2>{note && <p>{note}</p>}</div><span className="data-badge"><Database size={14} /> {dataLabel}</span></div><OceanMap points={points ?? fallback} kind={kind === "projection" ? "height" : kind} selected={selected} onPick={onPick} /></div>; }

function Home({ go }: { go: (v: ViewKey) => void }) {
  return <><section className="home-hero"><div className="hero-copy"><span className="eyebrow">SATELLITE OCEAN LAB · 월평균 SLA</span><h1>바다의 높이는<br /><em>어떻게 변해 왔을까?</em></h1><p>한반도 주변의 해수면 자료를 직접 고르고, 지도와 그래프에서 변화의 증거를 찾아보세요.</p><button className="primary-btn" onClick={() => go("point")}><Play size={17} fill="currentColor" /> 한 장소부터 탐구하기</button><div className="source-line"><span /><b>1993–2024</b> 위성 관측 기반 월평균 자료 · 변수: SLA</div></div><div className="hero-map"><MapResult kind="height" title="2024년 12월 해수면 고도 편차" note="색이 붉을수록 평소보다 높고, 푸를수록 낮습니다." /><div className="map-callout"><MousePointer2 size={17} /><span>지도를 움직이고 격자에 마우스를 올려 보세요</span></div></div></section><section className="home-path"><div><span className="eyebrow">오늘의 탐구 경로</span><h2>관찰에서 설명까지, 네 단계로 생각해요</h2></div><div className="path-cards">{[["01", "언제·어디를 볼까요?", "날짜와 위치를 선택합니다.", "date"], ["02", "어떻게 달라졌을까요?", "시계열과 추세를 비교합니다.", "point"], ["03", "어디가 더 빠를까요?", "공간별 변화율을 찾습니다.", "trend"], ["04", "왜 변했을까요?", "밀도와 질량 변화를 구분합니다.", "causes"]].map(([n, t, d, k]) => <button key={n} onClick={() => go(k as ViewKey)}><span>{n}</span><h3>{t}</h3><p>{d}</p><ArrowRight /></button>)}</div></section></>;
}

function DateView() {
  const [date, setDate] = useState("2024-12-18"); const [points, setPoints] = useState<ReturnType<typeof demoGrid>>(); const [usedDate, setUsedDate] = useState("2024-12-01"); const [label, setLabel] = useState("시연 모드"); const [error, setError] = useState("");
  const analyze = async () => { setError(""); try { const result = await apiGet<MapResponse>(`/api/map?date=${date}`); setPoints(flattenGrid(result.latitudes, result.longitudes, result.values)); setUsedDate(result.data_date); setLabel("활성 NetCDF"); } catch (e) { setError(e instanceof Error ? e.message : "자료를 불러오지 못했습니다."); setLabel("시연 모드"); } };
  return <><Flow /><div className="analysis-layout"><Panel hint="원하는 날짜를 고르면 가장 가까운 월평균 자료가 선택됩니다."><Field label="확인할 날짜" value={date} onChange={setDate} min={startDate} max={endDate} /><button className="primary-btn full" onClick={analyze}><Search size={17} /> 지도에서 확인</button>{error && <p className="inline-error">{error} 시연 자료를 유지합니다.</p>}<div className="mini-note"><Info size={16} /><p><b>월평균 자료예요.</b><br />하루의 높이가 아니라 한 달 관측값을 평균한 결과입니다.</p></div></Panel><MapResult kind="height" title={`${usedDate.slice(0, 7).replace("-", "년 ")}월 SLA 지도`} note={`요청 날짜 ${date} → 실제 사용 자료 ${usedDate}`} points={points} dataLabel={label} /></div><div className="result-row"><ResultStat label="선택한 날짜" value={date.replaceAll("-", ".")} /><ResultStat label="실제 자료 날짜" value={usedDate.replaceAll("-", ".")} /><ResultStat label="자료 간격" value="월평균" tone="cyan" /></div><Interpretation question="같은 달에도 바다마다 높이가 다른 까닭은 무엇일까요?">색은 해수면의 절대 높이가 아니라 장기 평균에서 벗어난 정도를 나타냅니다. 황해·남해·동해를 나누어 색의 패턴을 비교해 보세요.</Interpretation></>;
}

function PointView() {
  const [lat, setLat] = useState(38); const [lon, setLon] = useState(132); const [from, setFrom] = useState(startDate); const [to, setTo] = useState(endDate); const fallback = useMemo(() => demoSeries(lat, lon), [lat, lon]); const [series, setSeries] = useState(fallback); const [grid, setGrid] = useState({ lat: 38, lon: 132 }); const [trend, setTrend] = useState(3.9); const [label, setLabel] = useState("시연 모드"); const [error, setError] = useState(""); const displayedSeries = label === "시연 모드" ? fallback : series;
  const analyze = async () => { setError(""); try { const r = await apiGet<SeriesResponse>(`/api/point-series?start=${from}&end=${to}&lat=${lat}&lon=${lon}`); setSeries(r.series); setGrid(r.grid_location ?? { lat, lon }); setTrend(r.trend_mm_per_year); setLabel("활성 NetCDF"); } catch (e) { setError(e instanceof Error ? e.message : "자료를 불러오지 못했습니다."); setLabel("시연 모드"); } };
  return <><Flow active={2} /><div className="analysis-layout"><Panel hint="숫자를 입력하거나 지도에서 바다를 클릭하세요."><div className="field-grid"><Field label="시작 날짜" value={from} onChange={setFrom} min={startDate} max={to} /><Field label="종료 날짜" value={to} onChange={setTo} min={from} max={endDate} /></div><div className="coord-label"><span>위치 선택</span><small><MapPin size={13} /> 지도 클릭 가능</small></div><div className="field-grid"><Field label="위도 (°N)" type="number" value={lat} onChange={(v) => setLat(Number(v))} min={30} max={46} step="0.1" /><Field label="경도 (°E)" type="number" value={lon} onChange={(v) => setLon(Number(v))} min={117} max={139} step="0.1" /></div><div className="mini-map"><OceanMap points={[]} selected={{ lat, lon }} onPick={(a, o) => { setLat(a); setLon(o); }} /></div><button className="primary-btn full" onClick={analyze}><Activity size={17} /> 변화 분석하기</button>{error && <p className="inline-error">{error} 시연 자료를 유지합니다.</p>}</Panel><div className="visual-card chart-card"><div className="visual-head"><div><span className="step-kicker">STEP 3 · 결과</span><h2>선택 지점의 월평균 SLA 변화</h2><p>{from.slice(0, 7)} — {to.slice(0, 7)} · hover, 확대, 범례 켜기/끄기 가능</p></div><span className="data-badge"><Database size={14} /> {label}</span></div><PlotChart data={displayedSeries} /></div></div><div className="result-row"><ResultStat label="선택한 위치" value={`${lat.toFixed(2)}°N · ${lon.toFixed(2)}°E`} /><ResultStat label="가장 가까운 격자" value={`${grid.lat.toFixed(2)}°N · ${grid.lon.toFixed(2)}°E`} /><ResultStat label="선형 변화율" value={`${trend >= 0 ? "+" : ""}${trend.toFixed(2)} mm/년`} tone="coral" /></div><Interpretation question="작은 흔들림과 장기적인 변화는 어떻게 구분할까요?">옅은 선은 매달 변하는 값을, 굵은 선은 계절 변동을 줄인 12개월 평균을 보여줍니다. 점선의 기울기가 장기 변화율입니다.</Interpretation></>;
}

function RegionView() {
  const [from, setFrom] = useState(startDate); const [to, setTo] = useState(endDate); const fallback = useMemo(() => demoSeries(36, 128).map((d, i) => ({ ...d, monthly: d.trend + Math.sin(i / 8) * .006, moving: d.moving == null ? null : d.trend + Math.sin(i / 19) * .003 })), []); const [series, setSeries] = useState(fallback); const [trend, setTrend] = useState(3.42); const [label, setLabel] = useState("시연 모드"); const [error, setError] = useState("");
  const analyze = async () => { setError(""); try { const r = await apiGet<SeriesResponse>(`/api/area-series?start=${from}&end=${to}`); setSeries(r.series); setTrend(r.trend_mm_per_year); setLabel("활성 NetCDF"); } catch (e) { setError(e instanceof Error ? e.message : "자료를 불러오지 못했습니다."); } };
  return <><Flow active={2} /><div className="analysis-layout"><Panel hint="모든 바다 격자의 값을 한 달마다 평균합니다."><Field label="시작 날짜" value={from} onChange={setFrom} min={startDate} max={to} /><Field label="종료 날짜" value={to} onChange={setTo} min={from} max={endDate} /><div className="comparison"><MapPin /><div><b>한 장소</b><span>한 격자의 지역적 변화</span></div></div><div className="comparison active"><Globe2 /><div><b>전체 영역 평균</b><span>지역적 흔들림을 평균한 변화</span></div></div><button className="primary-btn full" onClick={analyze}><BarChart3 size={17} /> 영역 평균 계산</button>{error && <p className="inline-error">{error}</p>}</Panel><div className="visual-card chart-card"><div className="visual-head"><div><span className="step-kicker">STEP 3 · 결과</span><h2>분석 영역 전체의 평균 SLA</h2><p>117–139°E · 30–46°N의 유효한 바다 격자 평균</p></div><span className="data-badge"><Database size={14} /> {label}</span></div><PlotChart data={series} area /></div></div><div className="result-row"><ResultStat label="공간 범위" value="한반도 주변 전체" /><ResultStat label="평균 방식" value="유효한 바다 격자" /><ResultStat label="영역 평균 변화율" value={`${trend >= 0 ? "+" : ""}${trend.toFixed(2)} mm/년`} tone="coral" /></div><Interpretation question="한 지점보다 영역 평균 선이 더 매끄러운 이유는 무엇일까요?">서로 다른 곳의 일시적인 상승과 하강이 평균 과정에서 일부 상쇄됩니다. 그래서 넓은 지역의 공통적인 장기 신호가 더 잘 드러납니다.</Interpretation></>;
}

function TrendView() {
  const [from, setFrom] = useState(startDate); const [to, setTo] = useState(endDate); const [picked, setPicked] = useState({ lat: 37, lon: 129 }); const [points, setPoints] = useState<ReturnType<typeof demoGrid>>(); const [mean, setMean] = useState(3.42); const [label, setLabel] = useState("시연 모드"); const [error, setError] = useState("");
  const analyze = async () => { setError(""); try { const r = await apiGet<TrendResponse>(`/api/trend-map?start=${from}&end=${to}`); setPoints(flattenGrid(r.latitudes, r.longitudes, r.values)); setMean(r.area_mean); setLabel("활성 NetCDF"); } catch (e) { setError(e instanceof Error ? e.message : "자료를 불러오지 못했습니다."); } };
  const nearest = (points ?? demoGrid("trend")).reduce((best, p) => Math.hypot(p.lat - picked.lat, p.lon - picked.lon) < Math.hypot(best.lat - picked.lat, best.lon - picked.lon) ? p : best);
  return <><Flow active={2} /><div className="analysis-layout"><Panel hint="선택 기간 동안 각 격자에서 직선의 기울기를 계산합니다."><Field label="시작 날짜" value={from} onChange={setFrom} /><Field label="종료 날짜" value={to} onChange={setTo} /><div className="formula-box"><span>격자별 계산</span><b>SLA = 기울기 × 시간 + 시작값</b><small>기울기 × 1000 → mm/년</small></div><button className="primary-btn full" onClick={analyze}><Gauge size={17} /> 변화율 계산</button>{error && <p className="inline-error">{error}</p>}</Panel><MapResult kind="trend" title="공간별 해수면 변화율" note="지도 클릭 시 해당 격자의 변화율을 확인합니다." selected={picked} onPick={(lat, lon) => setPicked({ lat, lon })} points={points} dataLabel={label} /></div><div className="result-row"><ResultStat label="분석 영역 평균" value={`${mean >= 0 ? "+" : ""}${mean.toFixed(2)} mm/년`} /><ResultStat label="선택 격자" value={`${nearest.lat.toFixed(1)}°N · ${nearest.lon.toFixed(1)}°E`} /><ResultStat label="선택 위치 변화율" value={`${nearest.value >= 0 ? "+" : ""}${nearest.value.toFixed(2)} mm/년`} tone="coral" /></div><Interpretation question="이 지도는 ‘높은 곳’이 아니라 ‘빨리 변한 곳’을 보여줍니다.">0보다 큰 값은 해마다 높아지는 경향, 0보다 작은 값은 낮아지는 경향입니다. 한 달의 SLA 지도와 같은 색이라도 의미와 단위가 다릅니다.</Interpretation></>;
}

function CausesView() {
  return <><Flow active={1} /><section className="equation"><span>관측된 해수면 변화</span><b>≈</b><span className="steric">밀도 변화 <small>Steric</small></span><b>+</b><span className="mass">해수 질량 변화 <small>Ocean mass</small></span></section><div className="cause-grid"><article className="cause-card observed"><div><Activity /><span>관측</span></div><h3>전체 해수면 변화</h3><p>인공위성 고도계가 관측한 바다 표면의 변화입니다.</p><strong>Observed</strong></article><article className="cause-card steric"><div><Waves /><span>원인 성분 A</span></div><h3>바닷물의 밀도 변화</h3><p>수온과 염분이 바뀌면 같은 질량의 바닷물도 부피가 달라집니다.</p><strong>Thermosteric · Halosteric</strong></article><article className="cause-card mass"><div><Globe2 /><span>원인 성분 B</span></div><h3>바다로 들어온 물의 질량</h3><p>육상 빙하와 빙상이 녹거나 육지의 물 저장량이 달라진 효과입니다.</p><strong>Greenland · Antarctica · Glaciers · LWS</strong></article></div><section className="adapter-state"><div className="adapter-head"><div><Database /><div><span>실제 원인 자료 연결 상태</span><h2>원인 성분 데이터 어댑터 준비됨</h2></div></div><span className="status-dot">데이터 미연결</span></div><p>가짜 시계열은 표시하지 않습니다. NASA PO.DAAC HOMAGE 등 실제 Steric·Ocean mass 자료를 같은 월 단위로 연결하면 세 성분의 합과 관측값 차이를 자동 계산하도록 구성했습니다.</p><div className="adapter-questions"><div><span>01</span>밀도 변화는 전체의 얼마를 설명할까?</div><div><span>02</span>질량 증가는 전체의 얼마를 설명할까?</div><div><span>03</span>두 성분의 합과 관측값은 얼마나 비슷할까?</div></div></section><Interpretation question="두 원인 성분의 합이 관측값과 정확히 같지 않을 수도 있어요.">자료의 공간 범위와 기준 시기, 관측 오차가 서로 다를 수 있습니다. 비교할 때는 먼저 기간·단위·기준값이 같은지 확인해야 합니다.</Interpretation></>;
}

function ProjectionView() {
  const [tab, setTab] = useState<"projection" | "change">("projection"); const [from, setFrom] = useState(startDate); const [to, setTo] = useState(endDate); const [base, setBase] = useState(2024); const [projection, setProjection] = useState<ProjectionResponse>(); const [label, setLabel] = useState("시연 모드"); const [error, setError] = useState("");
  const analyze = async () => { setError(""); try { const r = await apiGet<ProjectionResponse>(`/api/projection?start=${from}&end=${to}&base_year=${base}&target_year=2100`); setProjection(r); setLabel("활성 NetCDF"); } catch (e) { setError(e instanceof Error ? e.message : "자료를 불러오지 못했습니다."); } };
  const points = projection ? flattenGrid(projection.latitudes, projection.longitudes, tab === "projection" ? projection.estimate_values : projection.change_mm_values) : undefined; const changePoints = projection ? flattenGrid(projection.latitudes, projection.longitudes, projection.change_mm_values) : undefined; const meanChange = changePoints ? changePoints.reduce((s, p) => s + p.value, 0) / changePoints.length : 260;
  return <><div className="warning"><Info /><div><b>단순 계산이며 기후 예측이 아닙니다.</b><p>이 결과는 실제 2100년 해수면을 정확히 예측한 것이 아닙니다. 과거의 선형 변화가 같은 속도로 계속된다고 가정한 단순 계산입니다.</p></div></div><div className="analysis-layout"><Panel hint="과거 자료의 기간과 비교 기준연도를 정합니다."><Field label="추세 시작" value={from} onChange={setFrom} /><Field label="추세 종료" value={to} onChange={setTo} /><Field label="비교 기준연도" type="number" value={base} onChange={(v) => setBase(Number(v))} /><div className="formula-box"><span>단순 외삽</span><b>2100년 값 = 기울기 × 2100 + 절편</b><small>미래의 가속·감속은 포함하지 않음</small></div><button className="primary-btn full" onClick={analyze}><Activity size={17} /> 2100년 값 계산</button>{error && <p className="inline-error">{error}</p>}</Panel><div><div className="tabs"><button className={tab === "projection" ? "active" : ""} onClick={() => setTab("projection")}>2100년 SLA</button><button className={tab === "change" ? "active" : ""} onClick={() => setTab("change")}>기준연도 대비 변화량</button></div><MapResult kind={tab} title={tab === "projection" ? "2100년 SLA 단순 추정" : `${base}년 대비 2100년 변화량`} note={`${from.slice(0,4)}–${to.slice(0,4)}년 선형 추세를 그대로 연장한 계산`} points={points} dataLabel={label} /></div></div><div className="result-row"><ResultStat label="기준연도" value={`${base}년`} /><ResultStat label="목표연도" value="2100년" /><ResultStat label="영역 평균 변화량" value={`+${(meanChange ?? 260).toFixed(0)} mm`} tone="coral" /></div><Interpretation question="왜 이 결과를 ‘예측’이라고 부르면 안 될까요?">실제 미래에는 온실가스 배출, 빙상 반응, 해류와 지반 변화 등으로 상승 속도가 달라집니다. 이 화면은 선형 추세라는 가정을 시험하는 활동입니다.</Interpretation></>;
}

function AdminView() {
  const [logged, setLogged] = useState(false); const [file, setFile] = useState<File | null>(null); const [checking, setChecking] = useState(false); const [checked, setChecked] = useState(false); const [candidate, setCandidate] = useState(""); const [validation, setValidation] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState(""); const pw = useRef<HTMLInputElement>(null);
  if (!logged) return <div className="login-card"><div className="login-mark"><LockKeyhole /></div><span className="eyebrow">교사용 데이터 관리</span><h2>관리자 로그인</h2><p>수업에 사용할 NetCDF 자료를 검사하고 활성화합니다.</p><label className="field"><span>관리자 비밀번호</span><input ref={pw} type="password" placeholder="비밀번호 입력" onKeyDown={(e) => e.key === "Enter" && setLogged(true)} /></label><button className="primary-btn full" onClick={() => setLogged(true)}>로그인</button><small>로컬 개발 환경에서는 임의의 비밀번호로 화면을 확인할 수 있습니다.</small></div>;
  const validate = async () => { if (!file) return; setChecking(true); setError(""); try { const form = new FormData(); form.append("file", file); const response = await fetch(`${API_URL}/api/admin/validate`, { method: "POST", headers: { Authorization: `Bearer ${pw.current?.value || "oceanlab"}` }, body: form }); const data = await response.json() as { detail?: string; candidate: string; validation: Record<string, unknown> }; if (!response.ok) throw new Error(data.detail); setCandidate(data.candidate); setValidation(data.validation); setChecked(true); } catch (e) { setError(e instanceof Error ? e.message : "파일 검사에 실패했습니다."); setChecked(false); } finally { setChecking(false); } };
  const activate = async () => { try { const response = await fetch(`${API_URL}/api/admin/activate/${candidate}`, { method: "POST", headers: { Authorization: `Bearer ${pw.current?.value || "oceanlab"}` } }); const data = await response.json() as { detail?: string }; if (!response.ok) throw new Error(data.detail); alert("활성 자료로 적용되었습니다."); } catch (e) { setError(e instanceof Error ? e.message : "적용하지 못했습니다."); } };
  const row = (key: string, fallback: string) => validation?.[key] == null ? fallback : String(validation[key]);
  return <><Flow active={checked ? 3 : file ? 1 : 0} /><div className="admin-grid"><section className="upload-card"><div className="panel-title"><div><span className="step-kicker">STEP 1 · 업로드</span><h2>NetCDF 자료 선택</h2></div><UploadCloud /></div><label className="dropzone"><input type="file" accept=".nc,.nc4,.netcdf" onChange={(e) => { setFile(e.target.files?.[0] ?? null); setChecked(false); }} /><UploadCloud /><b>{file ? file.name : "파일을 놓거나 눌러서 선택"}</b><span>NetCDF (.nc, .nc4) · 최대 2 GB</span></label><button className="primary-btn full" disabled={!file || checking} onClick={validate}>{checking ? "좌표와 변수를 검사하는 중…" : "파일 검사 시작"}</button>{error && <p className="inline-error">{error}</p>}</section><section className="validation-card"><div className="panel-title"><div><span className="step-kicker">STEP 2 · 검사 결과</span><h2>{checked ? "수업에 사용할 수 있는 자료예요" : "검사 대기 중"}</h2></div>{checked && <Check className="check" />}</div>{checked ? <div className="validation-list">{[["파일명", row("filename", file?.name ?? "-")], ["데이터 기간", `${row("time_start", "-")} — ${row("time_end", "-")}`], ["위도 범위", `${row("lat_min", "-")}° — ${row("lat_max", "-")}°`], ["경도 범위", `${row("lon_min", "-")}° — ${row("lon_max", "-")}°`], ["시간 간격", row("interval", "-")], ["변수 목록", Array.isArray(validation?.variables) ? validation.variables.join(", ") : "-"], ["SLA 존재 여부", validation?.has_sla ? "있음" : "없음"], ["SLA 단위", row("sla_unit", "-")]].map(([a,b]) => <div key={a}><span>{a}</span><b>{b}</b><Check /></div>)}</div> : <div className="empty-check"><Database /><p>파일을 선택하고 검사를 시작하면<br />기간, 좌표, 변수, 단위를 확인합니다.</p></div>}{checked && <button className="apply-btn" onClick={activate}><Check /> 이 자료를 활성 데이터로 적용</button>}</section></div><Interpretation question="활성 자료를 바꾸기 전에 무엇을 확인해야 할까요?">SLA 변수가 있고 단위가 m인지, 시간 간격이 월 단위인지, 수업에서 다룰 한반도 주변 범위를 포함하는지 확인하세요.</Interpretation></>;
}

export default function SeaLevelApp() {
  const [view, setView] = useState<ViewKey>("home"); const [mobile, setMobile] = useState(false); const [activeData, setActiveData] = useState(false); const meta = viewMeta[view]; const go = (v: ViewKey) => { setView(v); setMobile(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  useEffect(() => { void fetch(`${API_URL}/health`).then(async (r) => { if (!r.ok) throw new Error("offline"); return await r.json() as { active_dataset?: boolean }; }).then((d) => setActiveData(Boolean(d.active_dataset))).catch(() => setActiveData(false)); }, []);
  return <div className="app-shell"><header className="topbar"><button className="brand" onClick={() => go("home")}><span><Waves /></span><div><b>해수면 탐구실</b><small>SEA LEVEL INQUIRY LAB</small></div></button><div className={`dataset-status ${activeData ? "" : "demo"}`}><span /><div><small>현재 자료</small><b>{activeData ? "활성 NetCDF · 실제 관측 자료" : "내장 시연 자료 · 관측 자료 아님"}</b></div></div><button className="mobile-toggle" aria-label={mobile ? "탐구 메뉴 닫기" : "탐구 메뉴 열기"} onClick={() => setMobile(!mobile)}>{mobile ? <X /> : <Menu />}</button></header><div className="body-grid"><nav className={mobile ? "side-nav open" : "side-nav"}><div className="nav-caption">탐구 메뉴</div>{items.map((it) => <button key={it.key} className={view === it.key ? "active" : ""} onClick={() => go(it.key)}><it.icon /><span>{it.label}</span>{view === it.key && <ChevronRight className="chev" />}</button>)}<div className="nav-source"><Database /><div><span>데이터 원칙</span><p>시연 자료와 실제 관측 자료를 구분해 표시합니다.</p></div></div></nav><main className="main-content"><header className="page-head"><div><span className="eyebrow">{meta.eyebrow}</span>{view !== "home" && <><h1>{meta.title}</h1><p>{meta.desc}</p></>}</div>{view !== "home" && <span className="scope-chip"><Map size={15} /> 한반도 주변 117–139°E</span>}</header>{view === "home" && <Home go={go} />}{view === "date" && <DateView />}{view === "point" && <PointView />}{view === "region" && <RegionView />}{view === "trend" && <TrendView />}{view === "causes" && <CausesView />}{view === "projection" && <ProjectionView />}{view === "admin" && <AdminView />}</main></div></div>;
}
