%% Complete the 1993-01 through 2023-04 Groundwater fingerprint
clearvars;
clc;

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
preparedDir = fullfile(projectRoot, 'data', 'processed', ...
    'barystatic', 'source_loading');
outputDir = fullfile(projectRoot, 'data', 'processed', 'barystatic');
rawDir = fullfile(projectRoot, 'data', 'source', 'barystatic');
addpath(fullfile(scriptDir, 'lib'), '-begin');

config = struct( ...
    'sourceFile', fullfile(preparedDir, ...
        'groundwater_loading_1deg_monthly_196001_202304.nc'), ...
    'outputFile', fullfile(outputDir, ...
        'groundwater_fingerprint_1deg_monthly_199301_202304.nc'), ...
    'fingerprintVariable', 'groundwater_fingerprint', ...
    'componentKey', 'groundwater', ...
    'componentName', 'Groundwater Depletion', ...
    'title', 'Monthly groundwater-depletion sea-level fingerprints', ...
    'summary', ['Relative sea-level fingerprints generated from prepared ', ...
        'monthly Groundwater loading. Values after 2010-12 use grid-cell ', ...
        'linear extrapolation fitted over 1991-2010.'], ...
    'fingerprintLongName', ...
        'Groundwater-depletion relative sea-level fingerprint anomaly', ...
    'maskFile', fullfile(rawDir, 'ocean_mask', ...
        'landmask_181361.mat'), ...
    'sleDir', 'D:\GRACE_edu\Archive\Jeon', ...
    'harmonicsDir', 'D:\GRACE_edu\Archive\Simons', ...
    'maxDegree', 60, ...
    'expectedEnd', [2023 4 15 0 0 0], ...
    'monthLimit', inf);

result = build_sle_from_prepared_loading(config);
fprintf('\nGroundwater result: %d/%d months; max residual %.3e Gt\n', ...
    result.completedMonths, result.totalMonths, result.maxMassResidualGt);
