%% Build Antarctic, Greenland, and mountain-glacier fingerprints
clearvars;
clc;

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
sourceDir = fullfile(projectRoot, 'data', 'source', 'barystatic');
outputDir = fullfile(projectRoot, 'data', 'processed', 'barystatic');
addpath(fullfile(scriptDir, 'lib'), '-begin');

common = struct( ...
    'maskFile', fullfile(sourceDir, 'ocean_mask', ...
        'landmask_181361.mat'), ...
    'sleDir', 'D:\GRACE_edu\Archive\Jeon', ...
    'harmonicsDir', 'D:\GRACE_edu\Archive\Simons', ...
    'maxDegree', 60);

components(1) = componentConfig(common, ...
    fullfile(sourceDir, 'IB.mat'), 'IB_AIS', 'tv_r', ...
    fullfile(outputDir, ...
        'ais_fingerprint_1deg_monthly_199201_202012.nc'), ...
    'ais_fingerprint', 'antarctica', 'Antarctic Ice Sheet', ...
    'Monthly Antarctic ice-sheet sea-level fingerprints', ...
    ['Relative sea-level fingerprints generated from monthly IB_AIS ', ...
    'land loading with an elastic self-attracting and loading SLE model.'], ...
    'Antarctic ice-sheet relative sea-level fingerprint anomaly', ...
    348, [1992 1 15 0 0 0], [2020 12 15 0 0 0]);

components(2) = componentConfig(common, ...
    fullfile(sourceDir, 'IB.mat'), 'IB_GIS_C', 'tv_r', ...
    fullfile(outputDir, ...
        'greenland_fingerprint_1deg_monthly_199201_202012.nc'), ...
    'greenland_fingerprint', 'greenland', 'Greenland Ice Sheet', ...
    'Monthly Greenland ice-sheet sea-level fingerprints', ...
    ['Relative sea-level fingerprints generated from monthly IB_GIS_C ', ...
    'land loading with an elastic self-attracting and loading SLE model.'], ...
    'Greenland ice-sheet relative sea-level fingerprint anomaly', ...
    348, [1992 1 15 0 0 0], [2020 12 15 0 0 0]);

components(3) = componentConfig(common, ...
    fullfile(sourceDir, ...
        'Zemp_et_al_2019_Glacier_mass_change_kg_m2_1965_2016.mat'), ...
    'GLC', 'tv', ...
    fullfile(outputDir, ...
        'mountain_glaciers_fingerprint_1deg_monthly_196501_201612.nc'), ...
    'mountain_glaciers_fingerprint', 'mountain_glaciers', ...
    'Mountain Glaciers', ...
    'Monthly mountain-glacier sea-level fingerprints', ...
    ['Relative sea-level fingerprints generated from monthly GLC land ', ...
    'loading with an elastic self-attracting and loading SLE model.'], ...
    'Mountain-glacier relative sea-level fingerprint anomaly', ...
    624, [1965 1 15 0 0 0], [2016 12 15 0 0 0]);

results = repmat(struct('outputFile', '', 'completedMonths', 0, ...
    'totalMonths', 0, 'maxMassResidualGt', NaN), size(components));
for k = 1:numel(components)
    results(k) = build_sle_component_netcdf(components(k));
end

fprintf('\nIce-component build summary\n');
for k = 1:numel(components)
    fprintf('%-22s %4d/%4d months  max residual %.3e Gt\n', ...
        components(k).componentName, results(k).completedMonths, ...
        results(k).totalMonths, results(k).maxMassResidualGt);
end

function config = componentConfig(common, sourceFile, sourceVariable, ...
        timeVariable, outputFile, fingerprintVariable, componentKey, ...
        componentName, title, summary, fingerprintLongName, ...
        expectedMonths, expectedStart, expectedEnd)
config = common;
config.sourceFile = sourceFile;
config.sourceVariable = sourceVariable;
config.timeVariable = timeVariable;
config.outputFile = outputFile;
config.fingerprintVariable = fingerprintVariable;
config.componentKey = componentKey;
config.componentName = componentName;
config.title = title;
config.summary = summary;
config.fingerprintLongName = fingerprintLongName;
config.expectedMonths = expectedMonths;
config.expectedStart = expectedStart;
config.expectedEnd = expectedEnd;
end
