%% Complete the 1993-01 through 2017-12 DAM reservoir fingerprint
clearvars;
clc;

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
preparedDir = fullfile(projectRoot, 'data', 'processed', ...
    'barystatic', 'source_loading');
outputDir = fullfile(projectRoot, 'data', 'processed', 'barystatic');
rawDir = fullfile(projectRoot, 'data', 'source', 'barystatic');
addpath(fullfile(scriptDir, 'lib'), '-begin');

config = struct( ...
    'sourceFile', fullfile(preparedDir, ...
        'dam_loading_1deg_monthly_199301_201712.nc'), ...
    'outputFile', fullfile(outputDir, ...
        'dam_fingerprint_1deg_monthly_199301_201712.nc'), ...
    'fingerprintVariable', 'dam_fingerprint', ...
    'componentKey', 'dam_reservoir_storage', ...
    'componentName', 'DAM Reservoir Storage', ...
    'title', 'Monthly dam-reservoir sea-level fingerprints', ...
    'summary', ['Relative sea-level fingerprints generated from annual ', ...
        'DAM fields linearly interpolated over the 1993-01 through ', ...
        '2017-12 altimetry era. No temporal extrapolation is used.'], ...
    'fingerprintLongName', ...
        'Dam-reservoir relative sea-level fingerprint anomaly', ...
    'maskFile', fullfile(rawDir, 'ocean_mask', ...
        'landmask_181361.mat'), ...
    'sleDir', 'D:\GRACE_edu\Archive\Jeon', ...
    'harmonicsDir', 'D:\GRACE_edu\Archive\Simons', ...
    'maxDegree', 60, ...
    'expectedEnd', [2017 12 15 0 0 0], ...
    'monthLimit', inf);

result = build_sle_from_prepared_loading(config);
fprintf('\nDAM result: %d/%d months; max residual %.3e Gt\n', ...
    result.completedMonths, result.totalMonths, result.maxMassResidualGt);
