%% Complete the 1993-01 through 2022-12 seasonal-snow fingerprint
clearvars;
clc;

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
preparedDir = fullfile(projectRoot, 'data', 'processed', ...
    'barystatic', 'source_loading');
outputDir = fullfile(projectRoot, 'data', 'processed', 'barystatic');
rawDir = fullfile(projectRoot, 'data', 'source', 'barystatic');
addpath(fullfile(scriptDir, 'lib'), '-begin');

config = struct( ...
    'sourceFile', fullfile(preparedDir, ...
        'snow_loading_1deg_monthly_199301_202212.nc'), ...
    'outputFile', fullfile(outputDir, ...
        'snow_fingerprint_1deg_monthly_199301_202212.nc'), ...
    'fingerprintVariable', 'snow_fingerprint', ...
    'componentKey', 'seasonal_snow', ...
    'componentName', 'Seasonal Snow (ice sheets excluded)', ...
    'title', 'Monthly seasonal-snow sea-level fingerprints', ...
    'summary', ['Relative sea-level fingerprints from ERA5 seasonal snow ', ...
        'after excluding Antarctic and Greenland ice-sheet support. ', ...
        'Monthly states are referenced to the 2003-2010 per-cell mean.'], ...
    'fingerprintLongName', ...
        'Seasonal-snow relative sea-level fingerprint anomaly', ...
    'maskFile', fullfile(rawDir, 'ocean_mask', ...
        'landmask_181361.mat'), ...
    'sleDir', 'D:\GRACE_edu\Archive\Jeon', ...
    'harmonicsDir', 'D:\GRACE_edu\Archive\Simons', ...
    'maxDegree', 60, ...
    'expectedEnd', [2022 12 15 0 0 0], ...
    'monthLimit', inf);

result = build_sle_from_prepared_loading(config);
fprintf('\nSnow result: %d/%d months; max residual %.3e Gt\n', ...
    result.completedMonths, result.totalMonths, result.maxMassResidualGt);
