%% Build altimetry-era Groundwater and DAM sea-level fingerprints
clearvars;
clc;

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
sourceDir = fullfile(projectRoot, 'data', 'processed', ...
    'barystatic', 'source_loading');
outputDir = fullfile(projectRoot, 'data', 'processed', 'barystatic');
rawDir = fullfile(projectRoot, 'data', 'source', 'barystatic');
addpath(fullfile(scriptDir, 'lib'), '-begin');

common = struct( ...
    'maskFile', fullfile(rawDir, 'ocean_mask', 'landmask_181361.mat'), ...
    'sleDir', 'D:\GRACE_edu\Archive\Jeon', ...
    'harmonicsDir', 'D:\GRACE_edu\Archive\Simons', ...
    'maxDegree', 60, ...
    'monthLimit', inf);

components(1) = componentConfig(common, ...
    fullfile(sourceDir, ...
        'groundwater_loading_1deg_monthly_196001_202304.nc'), ...
    fullfile(outputDir, ...
        'groundwater_fingerprint_1deg_monthly_199301_202304.nc'), ...
    'groundwater_fingerprint', 'groundwater', 'Groundwater Depletion', ...
    'Monthly groundwater-depletion sea-level fingerprints', ...
    ['Relative sea-level fingerprints generated from prepared monthly ', ...
    'Groundwater loading. Values after 2010-12 use grid-cell linear ', ...
    'extrapolation fitted over 1991-2010.'], ...
    'Groundwater-depletion relative sea-level fingerprint anomaly', ...
    [2023 4 15 0 0 0]);

components(2) = componentConfig(common, ...
    fullfile(sourceDir, ...
        'dam_loading_1deg_monthly_199301_201712.nc'), ...
    fullfile(outputDir, ...
        'dam_fingerprint_1deg_monthly_199301_201712.nc'), ...
    'dam_fingerprint', 'dam_reservoir_storage', 'DAM Reservoir Storage', ...
    'Monthly dam-reservoir sea-level fingerprints', ...
    ['Relative sea-level fingerprints generated from annual DAM fields ', ...
    'linearly interpolated over the 1993-01 through 2017-12 altimetry era.'], ...
    'Dam-reservoir relative sea-level fingerprint anomaly', ...
    [2017 12 15 0 0 0]);

results = repmat(struct('outputFile', '', 'completedMonths', 0, ...
    'totalMonths', 0, 'maxMassResidualGt', NaN), size(components));
for k = 1:numel(components)
    results(k) = build_sle_from_prepared_loading(components(k));
end

fprintf('\nLand-water fingerprint summary\n');
for k = 1:numel(components)
    fprintf('%-24s %4d/%4d months  max residual %.3e Gt\n', ...
        components(k).componentName, results(k).completedMonths, ...
        results(k).totalMonths, results(k).maxMassResidualGt);
end

function config = componentConfig(common, sourceFile, outputFile, ...
        fingerprintVariable, componentKey, componentName, title, summary, ...
        fingerprintLongName, expectedEnd)
config = common;
config.sourceFile = sourceFile;
config.outputFile = outputFile;
config.fingerprintVariable = fingerprintVariable;
config.componentKey = componentKey;
config.componentName = componentName;
config.title = title;
config.summary = summary;
config.fingerprintLongName = fingerprintLongName;
config.expectedEnd = expectedEnd;
end
