%% Build only the Antarctic monthly sea-level fingerprint data set
clearvars;
clc;

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
sourceDir = fullfile(projectRoot, 'data', 'source', 'barystatic');
outputDir = fullfile(projectRoot, 'data', 'processed', 'barystatic');
addpath(fullfile(scriptDir, 'lib'), '-begin');

config = struct( ...
    'sourceFile', fullfile(sourceDir, 'IB.mat'), ...
    'sourceVariable', 'IB_AIS', ...
    'timeVariable', 'tv_r', ...
    'maskFile', fullfile(sourceDir, 'ocean_mask', ...
        'landmask_181361.mat'), ...
    'outputFile', fullfile(outputDir, ...
        'ais_fingerprint_1deg_monthly_199201_202012.nc'), ...
    'fingerprintVariable', 'ais_fingerprint', ...
    'componentKey', 'antarctica', ...
    'componentName', 'Antarctic Ice Sheet', ...
    'title', 'Monthly Antarctic ice-sheet sea-level fingerprints', ...
    'summary', ['Relative sea-level fingerprints generated from monthly ', ...
        'IB_AIS land loading with an elastic self-attracting and loading ', ...
        'SLE model.'], ...
    'fingerprintLongName', ...
        'Antarctic ice-sheet relative sea-level fingerprint anomaly', ...
    'sleDir', 'D:\GRACE_edu\Archive\Jeon', ...
    'harmonicsDir', 'D:\GRACE_edu\Archive\Simons', ...
    'maxDegree', 60, ...
    'expectedMonths', 348, ...
    'expectedStart', [1992 1 15 0 0 0], ...
    'expectedEnd', [2020 12 15 0 0 0]);

build_sle_component_netcdf(config);
