%% Recalculate only the first pending Groundwater month after correction
clearvars;
clc;

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
preparedDir = fullfile(projectRoot, 'data', 'processed', ...
    'barystatic', 'source_loading');
outputDir = fullfile(projectRoot, 'data', 'processed', 'barystatic');
rawDir = fullfile(projectRoot, 'data', 'source', 'barystatic');
addpath(fullfile(scriptDir, 'lib'), '-begin');

config = struct( ...
    'sourceFile', fullfile(preparedDir, ...
        'groundwater_loading_1deg_monthly_196001_202304.nc'), ...
    'outputFile', fullfile(outputDir, ...
        'groundwater_fingerprint_1deg_monthly_199301_202304.nc'), ...
    'fingerprintVariable', 'groundwater_fingerprint', ...
    'componentKey', 'groundwater', ...
    'componentName', 'Groundwater Depletion', ...
    'title', 'Monthly groundwater-depletion sea-level fingerprints', ...
    'summary', ['Relative sea-level fingerprints generated from prepared ', ...
        'monthly Groundwater loading. Values after 2010-12 use a 1991-2010 ', ...
        'grid-cell slope anchored to the observed 2010-12 grid.'], ...
    'fingerprintLongName', ...
        'Groundwater-depletion relative sea-level fingerprint anomaly', ...
    'maskFile', fullfile(rawDir, 'ocean_mask', ...
        'landmask_181361.mat'), ...
    'sleDir', 'D:\GRACE_edu\Archive\Jeon', ...
    'harmonicsDir', 'D:\GRACE_edu\Archive\Simons', ...
    'maxDegree', 60, ...
    'expectedEnd', [2023 4 15 0 0 0], ...
    'monthLimit', 1);

result = build_sle_from_prepared_loading(config);
timeNum = double(ncread(config.outputFile, 'time')) + datenum(1970, 1, 1);
update = double(ncread(config.outputFile, 'eustatic_equivalent'));
december = find(year(timeNum) == 2010 & month(timeNum) == 12);
january = find(year(timeNum) == 2011 & month(timeNum) == 1);
fprintf('2010-12 update: %+.6f mm\n', update(december));
fprintf('2011-01 update: %+.6f mm\n', update(january));
fprintf('Boundary step : %+.6f mm\n', update(january) - update(december));
fprintf('Completed     : %d/%d months\n', ...
    result.completedMonths, result.totalMonths);
