%% Calculate one 1993-01 SLE fingerprint for Snow and Soil Moisture
clearvars;
clc;

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));
preparedDir = fullfile(projectRoot, 'data', 'processed', ...
    'barystatic', 'source_loading');
outputDir = fullfile(projectRoot, 'data', 'processed', 'barystatic');
rawDir = fullfile(projectRoot, 'data', 'source', 'barystatic');
addpath(fullfile(scriptDir, 'lib'), '-begin');

common = struct( ...
    'maskFile', fullfile(rawDir, 'ocean_mask', 'landmask_181361.mat'), ...
    'sleDir', 'D:\GRACE_edu\Archive\Jeon', ...
    'harmonicsDir', 'D:\GRACE_edu\Archive\Simons', ...
    'maxDegree', 60, ...
    'monthLimit', 1);

snow = componentConfig(common, ...
    fullfile(preparedDir, ...
        'snow_loading_1deg_monthly_199301_202212.nc'), ...
    fullfile(outputDir, ...
        'snow_fingerprint_1deg_monthly_199301_202212.nc'), ...
    'snow_fingerprint', 'seasonal_snow', ...
    'Seasonal Snow (ice sheets excluded)', ...
    'Monthly seasonal-snow sea-level fingerprints', ...
    ['Relative sea-level fingerprints from ERA5 seasonal snow after ', ...
    'excluding Antarctic and Greenland ice-sheet support.'], ...
    'Seasonal-snow relative sea-level fingerprint anomaly', ...
    [2022 12 15 0 0 0]);

soil = componentConfig(common, ...
    fullfile(preparedDir, ...
        'soil_moisture_loading_1deg_monthly_199301_202212.nc'), ...
    fullfile(outputDir, ...
        'soil_moisture_fingerprint_1deg_monthly_199301_202212.nc'), ...
    'soil_moisture_fingerprint', 'soil_moisture', ...
    'Soil Moisture (ice sheets excluded)', ...
    'Monthly soil-moisture sea-level fingerprints', ...
    ['Relative sea-level fingerprints from ERA5 soil moisture after ', ...
    'excluding Antarctic and Greenland ice-sheet support.'], ...
    'Soil-moisture relative sea-level fingerprint anomaly', ...
    [2022 12 15 0 0 0]);

snowResult = build_sle_from_prepared_loading(snow);
soilResult = build_sle_from_prepared_loading(soil);
fprintf('\nSample status\n');
fprintf('Snow         : %d/%d months complete\n', ...
    snowResult.completedMonths, snowResult.totalMonths);
fprintf('Soil Moisture: %d/%d months complete\n', ...
    soilResult.completedMonths, soilResult.totalMonths);

function config = componentConfig(common, sourceFile, outputFile, ...
        fingerprintVariable, componentKey, componentName, title, summary, ...
        fingerprintLongName, expectedEnd)
config = common;
config.sourceFile = sourceFile;
config.outputFile = outputFile;
config.fingerprintVariable = fingerprintVariable;
config.componentKey = componentKey;
config.componentName = componentName;
config.title = title;
config.summary = summary;
config.fingerprintLongName = fingerprintLongName;
config.expectedEnd = expectedEnd;
end
